### PR TITLE
Append 'Pro' to Source Sans font styles

### PR DESCRIPTION
**Pull request by kevinSuttle**
Without these full names, the rendering can be off.

### CODE REVIEW

**Comment by ianstormtaylor** [comment]
do you have source sans pro installed locally on your machine? i think that might be falling back to the local copy, but if you disable it locally i think adding the `Pro` will break the fonts actually

**Comment by kevinSuttle** [comment]
Interesting. I know for both locally-installed and Google hosted fonts, the name follows the "- - Pro" convention, but Adobe's Edge Fonts and Typekit reference it by `source-sans-pro` 

http://www.google.com/fonts/specimen/Source+Sans+Pro

https://edgewebfonts.adobe.com/fonts#/?nameFilter=source&collection=source-sans-pro;source-code-pro

https://typekit.com/fonts/source-code-pro

Might be worth including both?

**Comment by ianstormtaylor** [comment]
in this case its using https://github.com/typefaces/source-sans-extra-light/blob/master/index.css but if lots of people have it locally installed it could be worth including both

**Comment by kevinSuttle** [comment]
Yeah, I see it being installed locally quite a bit since it's open source. Same with Open Sans. Up to you though.

**Comment by ianstormtaylor** [comment]
nice, if you update the pr to add the local version (with the non-local fallback) im happy to merge

**Comment by kevinSuttle** [comment]
The local versions aren't optimized for the web, so yes, that makes more sense.

**Comment by kevinSuttle** [comment]
Bump?

**Comment by ianstormtaylor** [comment]
sorry didn't realize you had added changes. i'm not sure if this will do anything now though because won't the first fonts always be hit in the stack? if the locals aren't optimized for web, then i assume we would just want to use the web versions instead

**Comment by kevinSuttle** [comment]
Sorry, I was under the impression that the "Source Sans" and "Source Code" were referencing the web fonts, so I moved the "Pro" names later into the stack in case the 3 seconds isn't enough to download and render. The local versions, while not optimized for web, are still better than say, Arial. :)

**Pull request merged**
